IDLE_TIME: 240

MOTD_DEFAULT: Bityard

MOTD_X_MIN: -341
MOTD_Y_MIN: 85
MOTD_Z_MIN: 259
MOTD_X_MAX: -341
MOTD_Y_MAX: 87
MOTD_Z_MAX: 264

SPAWN_GATEWAY_X: 77
SPAWN_GATEWAY_Y: 74
SPAWN_GATEWAY_Z: 324

SPAWN_GATEWAY_EXIT_X: 81
SPAWN_GATEWAY_EXIT_Y: 71
SPAWN_GATEWAY_EXIT_Z: 325

RETURN_GATEWAY_X: 0
RETURN_GATEWAY_Y: 0
RETURN_GATEWAY_Z: 0